### ISSUE TITLE
Torrent missing files..

### ISSUE THREAD

**Issue by 05warmupsdelayer** [proper1g1r/proper1g1r-collection#1]
You may need to delete torrent so archive.org recreates it?

Thanks!

**Comment by 05warmupsdelayer** [comment]
Yeah just delete it - something about how archive generates torrent file 

 See here 
https://www.reddit.com/r/Roms/comments/kmh1wv/archiveorg_fix_for_missing_files_in_the_torrent/

**Comment by proper1g1r** [comment]
[This comment](https://www.reddit.com/r/Roms/comments/kmh1wv/comment/jj821na/?utm_source=share&utm_medium=web2x&context=3) from the post you mentioned is a bit concerning, though, no? And would I have to delete the `.torrent` file every time I upload something new?

The more I read about archive.org and torrent on the Roms sub, the more it just seems to be broken as people are often recommending downloading things from there in different ways (like most comments [here](https://www.reddit.com/r/Roms/comments/o9k1yy/archiveorg_torrents_dont_contain_all_files) or [here](https://www.reddit.com/r/Roms/comments/s715fm/archive_org_torrents_are_truncated_when_i_try_and) or [here](https://www.reddit.com/r/Roms/comments/yuxohi/internet_archive_torrent_issue)). I'm not sure it's worth the effort trying to fix something seemingly just broken.

**Comment by 05warmupsdelayer** [comment]
The server won't generate a new torrent file until its deleted and a new file (any file like a junk text file) is uploaded, this is likely how the server is scripted so its not broken but rather designed this way to reduce the amount of torrent file generating - you have to trigger the server to make a new torrent file with the current files by deleting torrent file uploading new files. 

The advantage is people won't have an issue of missing files if they choose to download using torrent file and the downloads will be faster if people start seeding...anyways you can also disable torrents if you like as well...

https://help.archive.org/help/archive-bittorrents/

How to prevent an Archive Torrent from being made
Internet Archive BitTorrents are automatically made for community-contributed items in many collections, and automatically updated when item contents or metadata change.

If you prefer that your item not have an Archive Torrent made for it; or that items within a collection you maintain do not, you can prevent Torrents from being made by including the following metadata tag in your item:

noarchivetorrent=true

Note: adding this tag does not remove existing Torrents, those must be removed using the Item Manager item file management tool.

For instructions on how to edit an item or collection’s metadata, see the FAQ Uploading Content.

**Comment by proper1g1r** [comment]
Cool, thanks for all the info! Just one more question: there's definitely people right now downloading from the current torrent file, so what happens with their download if I delete it? That was another concern I had that I forgot to mention in my previous comment.

**Comment by 05warmupsdelayer** [comment]
Torrent clients won't grab torrent file again automatically so they likely will download some files fine...just not all the files. I guess torrent file was generated automatically after first batch was uploaded and these systems appear to have been missing...

Nintendo - Pokemon Mini.zip
Nintendo - Satellaview.zip
Nintendo - Sufami Turbo.zip
Nintendo - Super Nintendo Entertainment System.zip
Nokia - N-Gage (WIP).zip
Project EGG.zip
Sanyo - MBC-550 (Flux).zip
Sega - 32X.zip
Sega - Beena.zip
Sega - Mega Drive - Genesis.zip
Seta - Aleck64 (BigEndian).zip
Seta - Aleck64 (ByteSwapped).zip
Sharp - MZ-2200 (Waveform).zip
Sharp - X68000 (Flux).zip
Sinclair - ZX Spectrum +3.zip
TeleNova - Compis (Flux).zip
Tiger - Game.com.zip
Tiger - Gizmondo.zip
Toshiba - Pasopia (BIN).zip
Toshiba - Pasopia (WAV).zip
Yamaha - Copera.zip

(Torrent size = 70.9 GiB, but the archive site says "total size of requested files (85 GB) is too large for zip-on-the-fly")

I would just delete the torrent file, upload a junk txt file or something so archive will regenerate torrent with all the current files (downside of http torrent seeding I guess) and people will just have to download newly generated torrent if they want the above missing systems. You could also update the reddit post and let people know to get new torrent file and it should just resume what they have already downloaded + missing systems.

**Comment by proper1g1r** [comment]
I meant to update the thumbnail so I deleted the torrent file before doing it, let's see if it'll help ✌️

**Comment by 05warmupsdelayer** [comment]
good luck - if it doesn't auto generate again you may have to email them to request it

[My item does not have a torrent. How can I add one?](https://help.archive.org/help/archive-bittorrents/)
You would need to send a request to have a torrent generated to [info@archive.org](mailto:info@archive.org). Please include the URL of the item page.
