### ISSUE TITLE
Atari Lynx ".lyx" file extension isn't working

### ISSUE THREAD

**Issue by raiden6** [proper1g1r/proper1g1r-collection#3]
There's an issue with the Atari Lynx file extension ".lyx". I had to rename the rom to ".lnx" inside the zip file in order for Retroarch to load them.

**Comment by proper1g1r** [comment]
This collection is strict when it comes to only including files cataloged by No-Intro, and unfortunately ".lnx" files aren't well cataloged as it's mentioned in the README [here](https://github.com/proper1g1r/proper1g1r-collection?tab=readme-ov-file#systems-with-an-empty-dat-file-from-dat-o-matic).

You can check this yourself by going to the datomatic website and comparing the DAT files you get for LNX and LYX [here](https://datomatic.no-intro.org/index.php?page=download&op=dat&s=30).
