### ISSUE TITLE
Can't access

### ISSUE THREAD

**Issue by kishan-dhankecha** [proper1g1r/proper1g1r-collection#4]
As of recent ongoing incidents with archive.org we can't access content there. Also as of now, the site has come back but it's in read-only mode so no one is able to create a new account or log into an existing one.

I would like to know if there is an alternative place to find files. Thanks!

**Comment by proper1g1r** [comment]
Unfortunately there's no other source for downloading the collection for now :(

**Comment by kishan-dhankecha** [comment]
Okay, so we can open keep this open until we can access it again and add updates to this thread once we get some

**Comment by Demonmegi** [comment]
Log-In works now - Downloading works too.

**Comment by kishan-dhankecha** [comment]
But the [signup](https://archive.org/account/signup) page still redirects back to the [login page](https://archive.org/account/login). So there is no way to get this.

I also found another [URL](https://archive.org/account/login.createaccount.php) where I can access the signup page from the About page but after creating a new account from there I can not log in to that newly created account. The login page says the account not exists.

**Comment by demifiend9** [comment]
Since archive registration is not working, can someone just share the magnet link for the time being?

**Comment by Mafubar** [comment]
Here you go:

magnet:?xt=urn:btih:6bb5b6cc69a34c9b75b40cde4d8b5bc97279c146&dn=proper1g1r-collection&tr=http%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbt2.archive.org%3A6969%2Fannounce&ws=http://ia802806.us.archive.org/4/items/&ws=http://ia902806.us.archive.org/4/items/&ws=https://archive.org/download/

**Comment by proper1g1r** [comment]
It's back on!
