### ISSUE TITLE
Can't download FDS or QD ROMs.

### ISSUE THREAD

**Issue by yigitsalar** [proper1g1r/proper1g1r-collection#5]
It is straightforward, gives the error below.

### Item not available
The item is not available due to issues with the item's content.

**Comment by proper1g1r** [comment]
Thanks for reporting! I'll try reuploading to see if it helps.

**Comment by jenth13** [comment]
I'm getting this same error when trying to access the NES roms.

**Comment by yigitsalar** [comment]
So, I guess it is fixed by itself. I can download these right now.
